name: Checkout and Run Hello.bat

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find what directory you are in
        run: echo "Repository ${{ github.repository }}"

      - name: Run Hello.bat
        run: 
          hello.bat
